from .home_page import HomePage
from .account_page import AccountPage
from .mods_page import ModsPage
from .builds_page import BuildsPage
from .skins_page import SkinsPage
from .news_page import NewsPage
from .updates_page import UpdatesPage
from .servers_page import ServersPage
from .settings_page import SettingsPage
from .minecraft_page import MinecraftPage
from .ai_agent_page import AIAgentPage
